### PR TITLE
Reduce range gadget

### PR DESCRIPTION
**Pull request by BlackYoup**
This is not ready to merge and not intended to be merged, yet.

This is a PR to have an insight of the implementation of a gadget that can reduce the weapon range of an enemy ship.

Code is highly inspired from other gadgets, yet I did not fully copy paste because I don't like to copy paste things I don't understand.

There seem to be some formatting problem, please ignore them, I'll fix it on the final commit

### CODE REVIEW

**Comment by Noodlefu** [comment]
Looks good. Some notes:

- Don't use navigation controls for hotkeys.
- Use the gadget header located in /Gadgets to define variables like cooldown, strength, MT ship attribute's, etc, and don't set hard values in the object code. This allows for multiple versions to be created with varying attributes.

**Comment by BlackYoup** [comment]
The PR should now be in a better shape.

I've replaced the hotkey by `L`, which is used to load infantry. It may not be a definitive choice but at least it's not `W` anymore.

Let me know if something still doesn't feel right

**Review by Noodlefu — CHANGES_REQUESTED** [review]
Looks good from what I can see.

I would change the Gadget name however, as you've now moved what it does into the header of the object. GadgetModifierEW would work (and leave the header name as is).

After that I have no issues merging.

**Comment by BlackYoup** [comment]
Alright, now I fully understand your point :)

PR has been updated!

**Pull request merged**
