### PR TITLE
set BASE_FACTION_AI to 45

### PR DESCRIPTION
**Pull request by AudricStrauss**
I was able to sustain BASE_FACTION_AI at 80 on debug without issue. Should make the MV a bit more lived in and can serve as a test to see if the commit > update pipeline still works.

### CODE REVIEW

**Comment by rlyle** [comment]
Agree on that, been a long while since I tested the builds :)

**Comment by rlyle** [comment]
image

LOL... no builds since 2021 or so, this might take a bit to fix... I probably broke the connections to my server here at the house that does the builds.

**Comment by Noodlefu** [comment]
Last time VM4 was moved around I know we had a bunch of build failures due to non-build related issues (such as SMTP failing). @rlyle Give me a nudge if you need me to take a look once VM4 is up as I have some free time this week.

**Comment by Noodlefu** [comment]
I also wonder whether this'd be easier to control via the Settings class, as we can then adjust each process at start-up as needed...

**Comment by AudricStrauss** [comment]
It's common on a lot of other games to have settings like this stored in the ini so changes don't mean patches. I've not quite figured out how  to interact with the classes yet, but it would be a great idea to do it.

**Comment by Noodlefu** [comment]
@AudricStrauss the GameServer class gets initiated from a ServerContext class that itself pulls in from the Settings class (see DarkSpaceServer.cpp L146). This could, in theory, pull in and build a globally accessible value (via an accessor function) that is then referenced when AI are spawned via gameContext->getMaxAi() or something along those lines, and would benefit from being per-server-based values (so we could lower some, and increase others).

**Pull request merged**
